### ISSUE TITLE
Scrollbar Styling

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#74]
In this issue, I will propose styling the scrollbars on SkyCrypt

## The Problem

the problem with unstyled scrollbars is that they are white on most browsers which clashes with the dark esthetic of the site.

![image](https://user-images.githubusercontent.com/44071655/94199610-14ba1180-fe87-11ea-8866-140ad2902793.png)

notice how the scrollbars are the same contrast as the text drawing attention away from the content to the scrollbars.

## My Solution

add styling to the scrollbars with [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) and [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color)

however ::-webkit-scrollbar also affects mobile which looks weird because on mobile people expect to have the auto-hide zero-width scrollbar that comes by default.

The solution is to detect whether the scrollbar has a width in javascript when the page first loads and if it does then add the styles.

```javascript
// checks if the scrollbar has a width should be true with desktop style scrollbars
if (window.innerWidth > document.documentElement.clientWidth) {
  document.documentElement.classList.add('style-scrollbar');
} else {
  document.documentElement.classList.remove('style-scrollbar');
}
```
```css
.style-scrollbar {
    scrollbar-color: var(--icon-hex) #323232;
}

.style-scrollbar *::-webkit-scrollbar-track
{
    border-radius: 12px;
    background-color: rgba(60,60,60,0.5);
}

.style-scrollbar *::-webkit-scrollbar
{
    width: 12px;
    height: 12px;
}

.style-scrollbar *::-webkit-scrollbar-thumb
{
    border-radius: 12px;
    background-color: var(--icon-hex);
}

.style-scrollbar body::-webkit-scrollbar
{
    background-color: #282828;
}

@media (max-width: 900px){
    .style-scrollbar #nav_bar_line {
        bottom: 9px;
    }
    .style-scrollbar #nav_items_container {
        padding-bottom: 10px;
    }
}

.style-scrollbar #nav_items_container::-webkit-scrollbar-track
{
    background-color: transparent;
}

.style-scrollbar #nav_items_container::-webkit-scrollbar
{
    height: 8px;
}
```
here is what it looks like on Chrome (WebKit).
![image](https://user-images.githubusercontent.com/44071655/94199540-f94f0680-fe86-11ea-8d70-5e2e1b8f3d22.png)

and here is what it looks like on Firefox (non-WebKit).
![image](https://user-images.githubusercontent.com/44071655/94201292-cfe3aa00-fe89-11ea-8d95-cdc1ad3618c9.png)
